### ISSUE TITLE
UI change

### ISSUE THREAD

**Issue by twu1579** [NG-Development/ngdevelopment#44]
Add a menu bar for import/export files
Change buttons to display on the side
Change Colors

**Comment by jacobfij** [comment]
So just for absolute clarity, I have a few questions.  
1.) What exactly do you want the menu bar for import/export to have? There's already a button for importing, would you want this menu bar to replace that? Or do you just mean like a sidebar of imported models?
2.) You want the buttons moved from the bottom of the screen to the side. Would you prefer the left or right side?
3.) What exactly do you want me to change the color of? The entire area, containing the buttons? Just the buttons? And what colors do you want?

**Comment by twu1579** [comment]
All the buttons should be placed on the menu bar there's no longer a need for them on the side.
The functionality should stay the same.
Just ignore the change colors it's fine as is right now.
